[package]
name = "lfg"
version = "0.1.0"
authors = ["Celeo <mattboulanger@fastmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
log = "0.4.11"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_yaml = "0.8.13"
